VERSION = FINAL
TERRITORY = USA
USER = CDBUILD
FILE_SYSTEM = CD

boot:
	$(MAKE) -C boot VERSION=$(VERSION) TERRITORY=$(TERRITORY) USER=$(USER) FILE_SYSTEM=$(FILE_SYSTEM)
spongey:
	$(MAKE) -C src VERSION=$(VERSION) TERRITORY=$(TERRITORY) USER=$(USER) FILE_SYSTEM=$(FILE_SYSTEM)

clean:
	$(MAKE) -C boot clean
	$(MAKE) -C src clean

all:
	$(MAKE) -C boot VERSION=$(VERSION) TERRITORY=$(TERRITORY) USER=$(USER) FILE_SYSTEM=$(FILE_SYSTEM)
	$(MAKE) -C src VERSION=$(VERSION) TERRITORY=$(TERRITORY) USER=$(USER) FILE_SYSTEM=$(FILE_SYSTEM)
	
# declare phony rules
.PHONY: boot spongey \
		clean all
